import { ThemeProvider } from "@/components/ThemeProvider";
import "./globals.css";
import { Sono, Noto_Serif_Display } from 'next/font/google';

// Using Google Fonts with Next.js
const sono = Sono({
  weight: ['200', '300', '400', '500', '600', '700', '800'], // Specify the desired weights
  subsets: ['latin'],
  variable: '--font-sono',
});

const notoSerifDisplay = Noto_Serif_Display({
  weight: ['200', '300', '400', '500', '600', '700', '800'], // Specify the desired weights
  subsets: ['latin'],
  variable: '--font-noto-serif-display',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sono.variable} ${notoSerifDisplay.variable} bg-white text-zinc-600 dark:bg-black dark:text-zinc-200 antialiased`}
      >
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
